development:
  adapter: 'mysql2'
  database: 'gem_tracker_project_development'
  username: 'root'
  password:

test:
  adapter: 'mysql2'
  database: 'gem_tracker_project_test'
  username: 'root'
  password:

production:
  adapter: 'mysql2'
  database: 'gem_tracker_project_development'
  username: 'root'
  password:  
